export interface Project {
  id: string;
  slug: string;
  title: string;
  shortDescription: string;
  overview: string;
  problem: string;
  solution: string;
  features: string[];
  techStack: string[];
  impact: string[];
  image: string;
}

export const projects: Project[] = [
{
  id: '1',
  slug: 'car-service-management',
  title: 'Car Service Management System',
  shortDescription:
  'End-to-end booking and management platform for auto service centers.',
  overview:
  'A comprehensive management system designed for a network of car service centers to handle bookings, track service progress in real-time, and process payments seamlessly.',
  problem:
  'The client was relying on manual ledgers and disjointed WhatsApp messages to manage customer bookings. This led to double-bookings, lost revenue, and poor customer communication regarding service status.',
  solution:
  'We developed a centralized platform that allows customers to book slots online, provides mechanics with a digital checklist, and automates status updates to customers via SMS and email.',
  features: [
  'Online booking management with calendar integration',
  'Real-time service tracking for customers',
  'M-Pesa and credit card payment integration',
  'Automated SMS and email notifications',
  'Inventory management for spare parts'],

  techStack: ['React', 'Node.js', 'MySQL', 'Socket.IO', 'Tailwind CSS'],
  impact: [
  '60% efficiency improvement in daily operations',
  'Zero double-bookings since launch',
  '35% increase in customer retention due to better communication'],

  image:
  'https://images.unsplash.com/photo-1632823471565-1ec2a808eb21?auto=format&fit=crop&q=80&w=1000'
},
{
  id: '2',
  slug: 'ai-learning-management',
  title: 'AI Learning Management System',
  shortDescription:
  'Intelligent educational platform with personalized learning paths.',
  overview:
  'An advanced LMS that leverages artificial intelligence to adapt to individual student learning paces, providing custom content recommendations and predictive performance analytics.',
  problem:
  'A mid-sized educational institution struggled with a one-size-fits-all curriculum that left advanced students bored and struggling students behind, resulting in high dropout rates.',
  solution:
  'We built an AI-driven platform that assesses student proficiency in real-time and dynamically adjusts the difficulty and format of upcoming modules to optimize learning outcomes.',
  features: [
  'Personalized learning paths generated by AI',
  'Smart content recommendations based on performance',
  'Real-time progress tracking and analytics dashboard',
  'Automated grading for standard assessments',
  'Interactive video and text modules'],

  techStack: ['React', 'Node.js', 'SQLite', 'OpenAI API', 'Framer Motion'],
  impact: [
  'Significantly improved learning outcomes across all demographics',
  '40% reduction in student dropout rates',
  'Saved teachers an average of 15 hours per week on grading'],

  image:
  'https://images.unsplash.com/photo-1501504905252-473c47e087f8?auto=format&fit=crop&q=80&w=1000'
},
{
  id: '3',
  slug: 'school-management-system',
  title: 'School Management System',
  shortDescription:
  'Comprehensive administrative platform for educational institutions.',
  overview:
  'A robust, scalable system designed to digitize and streamline all administrative and academic processes for K-12 schools.',
  problem:
  'School administrators were drowning in paperwork, making it difficult to track attendance accurately, generate report cards efficiently, and communicate effectively with parents.',
  solution:
  "We deployed a unified system that digitizes student records, automates attendance tracking via biometric integration, and provides a secure portal for parents to monitor their child's progress.",
  features: [
  'Digital student and staff records management',
  'Automated attendance tracking',
  'Dynamic grading and report card generation',
  'Secure parent portal with real-time updates',
  'Internal messaging and announcement system'],

  techStack: ['React', 'Node.js', 'MySQL', 'Express', 'Redis'],
  impact: [
  'Reduced manual administrative workload by 70%',
  'Eliminated paper waste for report cards and notices',
  'Improved parent engagement by 85%'],

  image:
  'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&q=80&w=1000'
},
{
  id: '4',
  slug: 'consultancy-website',
  title: 'Consultancy Website',
  shortDescription:
  'High-conversion corporate web presence for a financial firm.',
  overview:
  'A premium, SEO-optimized corporate website designed to establish authority, showcase services, and capture high-quality leads for a top-tier financial consultancy.',
  problem:
  "The client's previous website was outdated, slow, and failed to reflect their premium market positioning, resulting in a high bounce rate and low lead generation.",
  solution:
  'We designed and developed a modern, lightning-fast website with a focus on user experience, clear value propositions, and strategic conversion points.',
  features: [
  'Professional, high-end UI/UX design',
  'Dynamic service showcase and case study portfolio',
  'Integrated contact and lead capture forms',
  'SEO optimized architecture',
  'CMS integration for easy content updates'],

  techStack: ['React', 'Tailwind CSS', 'Framer Motion', 'Vite'],
  impact: [
  '300% increase in organic traffic within 3 months',
  'Doubled the conversion rate of site visitors to leads',
  'Significantly improved brand perception and trust'],

  image:
  'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=1000'
}];